export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const GET_COMPANIES_REQUESTED = "GET_COMPANIES_REQUESTED";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAILED = "GET_COMPANIES_FAILED";

export const ADD_COMPANY_REQUESTED = "ADD_COMPANY_REQUESTED";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILED = "ADD_COMPANY_FAILED";

export const UPDATE_COMPANY_REQUESTED = "UPDATE_COMPANY_REQUESTED";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAILED = "UPDATE_COMPANY_FAILED";

export const SET_MODAL_FLAG = "SET_MODAL_FLAG";
export const MODAL_OPEN = "MODAL_OPEN";
export const SET_SELECTED_EDIT = "SET_SELECTED_EDIT";
export const SET_SELECTED_ID = "SET_SELECTED_ID";
export const ADD_OPEN_MODAL = "ADD_OPEN_MODAL";

export const GET_SINGLE_COMPANY = "GET_SINGLE_COMPANY";
export const GET_SINGLE_COMPANY_FAILED = "GET_SINGLE_COMPANY_FAILED";
export const GET_SINGLE_COMPANY_SUCCESS = "GET_SINGLE_COMPANY_SUCCESS";
