export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const GET_COMPANIES_REQUESTED = "GET_COMPANIES_REQUESTED";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAILED = "GET_COMPANIES_FAILED";

export const ADD_COMPANY_REQUESTED = "ADD_COMPANY_REQUESTED";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILED = "ADD_COMPANY_FAILED";

export const SET_MODAL_FLAG = "SET_MODAL_FLAG";
export const MODAL_OPEN = "MODAL_OPEN";
